[build.environment]
  NETLIFY_USE_YARN_WORKSPACES = "false"

[functions]
directory = "netlify/functions"
[[headers]]
  for = "index.html"
  [headers.values]
    Cache-Control = "public, max-age=60, must-revalidate"
    
[build]
  base = "."
  command = "cd local_frame/flat_minecraft && vite build"
  publish = "local_frame/flat_minecraft/dist"
  functions = "local_frame/flat_minecraft/netlify/functions"
