[functions]
directory = "netlify/functions"
[[headers]]
  for = "index.html"
  [headers.values]
    Cache-Control = "public, max-age=60, must-revalidate"
    
[build]
  command = "npm run build"
  publish = "dist"

