[functions]
directory = "scripts/functions"
[[headers]]
  for = "index.html"
  [headers.values]
    Cache-Control = "public, max-age=60, must-revalidate"
    
[build]
  base = "local_frame/flat_minecraft/1.0-Alpha/game"
  command = "npm ci && npm run build"
  publish = "dist"
